const Data = [
  {
    id: 1,
    type: 'Design',
    priority: 'High',
    name: 'portfolio website revamp',
    assignedTo: 'Michael Davis',
    status: 'In Progress',
    submitDate: '18/Apr/2024',
    time: '4d',
    progress: 4,
    link: 'GitHub1',
    task: [
      {
        id: 1,
        task: 'Task 1',
        checked: false,
      },
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 2,
    type: 'Development',
    priority: 'Medium',
    name: 'mobile app feature integration',
    assignedTo: 'Emma Johnson',
    status: 'In Progress',
    submitDate: '02/May/2024',
    time: '1w',
    progress: 8.5,
    link: 'GitHub2',
    task: [
      {id: 1, task: 'Task 4', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 3,
    type: 'Marketing',
    priority: 'Low',
    name: 'email campaign optimization',
    assignedTo: 'Christopher Miller',
    status: 'Open',
    submitDate: '14/May/2024',
    time: '2d',
    progress: 0,
    link: 'GitHub3',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 4,
    type: 'Testing',
    priority: 'High',
    name: 'software testing for release',
    assignedTo: 'Olivia Harris',
    status: 'Completed',
    submitDate: '30/May/2024',
    time: '3d',
    progress: 1,
    link: 'GitHub4',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 5,
    type: 'Support',
    priority: 'Medium',
    name: 'customer query resolution',
    assignedTo: 'William Clark',
    status: 'Over Due',
    submitDate: '10/Jun/2024',
    time: '1w',
    progress: 8,
    link: 'GitHub5',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 6,
    type: 'Design',
    priority: 'Low',
    name: 'branding materials creation',
    assignedTo: 'Sophia Taylor',
    status: 'Open',
    submitDate: '25/Jun/2024',
    time: '4d',
    progress: 7,
    link: 'GitHub6',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 7,
    type: 'Development',
    priority: 'High',
    name: 'web application security audit',
    assignedTo: 'Daniel Brown',
    status: 'Completed',
    submitDate: '08/Jul/2024',
    time: '2d',
    progress: 10,
    link: 'GitHub7',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 8,
    type: 'Marketing',
    priority: 'Medium',
    name: 'product launch campaign',
    assignedTo: 'Ava Wilson',
    status: 'In Progress',
    submitDate: '20/Jul/2024',
    time: '1w',
    progress: 8,
    link: 'GitHub8',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 9,
    type: 'Testing',
    priority: 'Low',
    name: 'performance testing for app',
    assignedTo: 'James Anderson',
    status: 'Open',
    submitDate: '05/Aug/2024',
    time: '3d',
    progress: 0,
    link: 'GitHub9',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
  {
    id: 10,
    type: 'Support',
    priority: 'High',
    name: 'escalated ticket resolution',
    assignedTo: 'Lily Moore',
    status: 'In Progress',
    submitDate: '18/Aug/2024',
    time: '1w',
    progress: 7.2,
    link: 'GitHub10',
    task: [
      {id: 1, task: 'Task 1', checked: false},
      {id: 2, task: 'Task 2', checked: false},
      {id: 3, task: 'Task 3', checked: false},
    ],
  },
];

export default Data;
