const EmployeeData = [
  {
    id: 1,
    name: 'John Doe',
    workingType: 'Full-time',
    developerType: 'Frontend',
    organization: 'ABC Corporation',
    technology: 'Python, JavaScript',
    mobileNo: '+1234567890',
    email: 'john.doe@example.com',
    city: 'New York',
    address: '123 Main St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 2,
    name: 'Jane Smith',
    workingType: 'Part-time',
    developerType: 'Backend',
    organization: 'XYZ Corp',
    technology: 'Java, SQL',
    mobileNo: '+1987654321',
    email: 'jane.smith@example.com',
    city: 'Los Angeles',
    address: '456 Elm St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 3,
    name: 'Michael Johnson',
    workingType: 'Contractor',
    developerType: 'Fullstack',
    organization: 'Tech Innovations LLC',
    technology: 'C++, HTML',
    mobileNo: '+1122334455',
    email: 'michael.j@example.com',
    city: 'Chicago',
    address: '789 Oak Ave',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 4,
    name: 'Emily Brown',
    workingType: 'Freelancer',
    developerType: 'Frontend',
    organization: '',
    technology: 'Ruby, CSS',
    mobileNo: '+1555666777',
    email: 'emily.b@example.com',
    city: 'Houston',
    address: '101 Pine St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 5,
    name: 'David Lee',
    workingType: 'Full-time',
    developerType: 'Backend',
    organization: 'Tech Giant Inc.',
    technology: 'Java, React',
    mobileNo: '+1444333222',
    email: 'david.lee@example.com',
    city: 'San Francisco',
    address: '555 Maple Ave',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 6,
    name: 'Sarah Wilson',
    workingType: 'Part-time',
    developerType: 'Frontend',
    organization: 'E-commerce Solutions',
    technology: 'PHP, MySQL',
    mobileNo: '+1666777888',
    email: 'sarah.w@example.com',
    city: 'Miami',
    address: '777 Cedar St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 7,
    name: 'James Taylor',
    workingType: 'Full-time',
    developerType: 'Fullstack',
    organization: 'Digital Services Corp',
    technology: 'Python, Django',
    mobileNo: '+1223444555',
    email: 'james.taylor@example.com',
    city: 'Seattle',
    address: '888 Pine St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 8,
    name: 'Emma Garcia',
    workingType: 'Contractor',
    developerType: 'Backend',
    organization: 'Creative Solutions LLC',
    technology: 'JavaScript, Angular',
    mobileNo: '+1999888777',
    email: 'emma.g@example.com',
    city: 'Boston',
    address: '999 Elm St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 9,
    name: 'William Martinez',
    workingType: 'Full-time',
    developerType: 'Frontend',
    organization: 'Tech Innovations LLC',
    technology: 'C#, ASP.NET',
    mobileNo: '+1888777666',
    email: 'william.m@example.com',
    city: 'Atlanta',
    address: '333 Oak Ave',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
  {
    id: 10,
    name: 'Olivia Adams',
    workingType: 'Intern',
    developerType: 'Frontend',
    organization: 'Tech Startup XYZ',
    technology: 'HTML, CSS',
    mobileNo: '+1777666555',
    email: 'olivia.a@example.com',
    city: 'Denver',
    address: '222 Maple St',
    Eid: Math.floor(1000000000 + Math.random() * 9000000000),
  },
];

export default EmployeeData;
